name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildAndTestiOS:
    name: Build & Test iOS
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, macOS-latest]
        xcode: ['12.1', '12.5']
        devices: ['iPhone 12 Pro Max', 'iPod touch (7th generation)', 'iPad (8th generation)']
        exclude:
          - os: macos-10.15
            xcode: '12.5'
    runs-on: ${{matrix.os}}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
    - name: Build & Test
      run: xcodebuild -scheme 'SMHSSchedule (iOS) Release' test -destination 'platform=iOS Simulator,name=${{matrix.devices}}'
  Swift_format_lint:
    name: Check swiftformat
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        
      - name: Install Swiftformat
        run: brew install swiftformat

      - name: Format Swift code
        run: swiftformat --verbose . --swiftversion 5.2
